# Strings

Topics:
1. How to get a string
2. String interpolation
3. String concatenation

## How to get a string

Enclose your characters in " " or """ """!

In [ ]:
s1 = "I am a string."

In [1]:
s2 = """I am also a string. """
println(s2)

I am also a string. 


There are a couple functional differences between strings enclosed in single and triple quotes. <br>
One difference is that, in the latter case, you can use quotation marks within your string.

In [13]:
"Here, we get an "error" because it's ambiguous where this string ends "

LoadError: syntax: cannot juxtapose string literal

In [14]:
"""Look, Mom, no "errors"!!! """

"Look, Mom, no \"errors\"!!! "

Note that ' ' define a character, but NOT a string!

In [15]:
typeof('a')

Char

In [16]:
'We will get an error here'

LoadError: syntax: invalid character literal

## String interpolation

We can use the $ sign to insert existing variables into a string and to evaluate expressions within a string. <br>
Below is an example that contains some highly sensitive personal information.

In [17]:
name = "Jane"
num_fingers = 10
num_toes = 10

10

In [18]:
println("Hello, my name is $name.")
println("I have $num_fingers fingers and $num_toes toes.")

Hello, my name is Jane.
I have 10 fingers and 10 toes.


In [19]:
 println("That is $(num_fingers + num_toes) digits in all!!")

That is 20 digits in all!!


## String concatenation

Below are three ways we can concatenate strings! <br><br>
The first way is to use the `string()` function. <br>
`string()` converts non-string inputs to strings.

In [20]:
s3 = "How many cats ";
s4 = "is too many cats?";
😺 = 10

10

In [21]:
string(s3, s4)

"How many cats is too many cats?"

In [22]:
string("I don't know, but ", 😺, " is too few.")

"I don't know, but 10 is too few."

We can also use `*` for concatenation!

In [23]:
s3*s4

"How many cats is too many cats?"

### Exercises

#### 2.1 
Create a string that says "hi" 1000 times, first with `repeat` and then with the exponentiation operator, which can call `*` under the hood.

In [26]:
?repeat

search: repeat



```
repeat(A::AbstractArray, counts::Integer...)
```

Construct an array by repeating array `A` a given number of times in each dimension, specified by `counts`.

# Examples

```jldoctest
julia> repeat([1, 2, 3], 2)
6-element Array{Int64,1}:
 1
 2
 3
 1
 2
 3

julia> repeat([1, 2, 3], 2, 3)
6×3 Array{Int64,2}:
 1  1  1
 2  2  2
 3  3  3
 1  1  1
 2  2  2
 3  3  3
```

---

```
repeat(A::AbstractArray; inner=ntuple(x->1, ndims(A)), outer=ntuple(x->1, ndims(A)))
```

Construct an array by repeating the entries of `A`. The i-th element of `inner` specifies the number of times that the individual entries of the i-th dimension of `A` should be repeated. The i-th element of `outer` specifies the number of times that a slice along the i-th dimension of `A` should be repeated. If `inner` or `outer` are omitted, no repetition is performed.

# Examples

```jldoctest
julia> repeat(1:2, inner=2)
4-element Array{Int64,1}:
 1
 1
 2
 2

julia> repeat(1:2, outer=2)
4-element Array{Int64,1}:
 1
 2
 1
 2

julia> repeat([1 2; 3 4], inner=(2, 1), outer=(1, 3))
4×6 Array{Int64,2}:
 1  2  1  2  1  2
 1  2  1  2  1  2
 3  4  3  4  3  4
 3  4  3  4  3  4
```

---

```
repeat(s::AbstractString, r::Integer)
```

Repeat a string `r` times. This can be written as `s^r`.

See also: [`^`](@ref)

# Examples

```jldoctest
julia> repeat("ha", 3)
"hahaha"
```

---

```
repeat(c::AbstractChar, r::Integer) -> String
```

Repeat a character `r` times. This can equivalently be accomplished by calling [`c^r`](@ref ^).

# Examples

```jldoctest
julia> repeat('A', 3)
"AAA"
```


In [31]:
println(repeat("hi",10))

println("hi"^10)

hihihihihihihihihihi
hihihihihihihihihihi


#### 2.2 
Declare two variables

```julia
a = 3
b = 4
```
and use them to create two strings:
```julia
"3 + 4"
"7"
```

In [34]:
a=3
b=4

println(String("$a + $b"))
println(String("$(a + b)"))




3 + 4
7
